version: "3.8"
services:
  app_web:
    container_name: app_web
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - "127.0.0.1:3030:3030"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    external: true
